// Generated by CoffeeScript 1.6.3
(function() {
  var GE, globals,
    __slice = [].slice;

  globals = this;

  GE = {};

  globals.GE = GE;

  GE.makeConstantSet = function() {
    var obj, value, values, _i, _len;
    values = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    obj = {
      contains: function(value) {
        return value in obj;
      }
    };
    for (_i = 0, _len = values.length; _i < _len; _i++) {
      value = values[_i];
      obj[value] = value;
    }
    return Object.freeze(obj);
  };

  GE.logLevels = GE.makeConstantSet("ERROR", "WARN", "INFO", "LOG");

  GE.signals = GE.makeConstantSet("DONE", "ERROR");

  GE.indexOf = function(collection, value) {
    var k, v;
    for (k in collection) {
      v = collection[k];
      if (_.isEqual(v, value)) {
        return k;
      }
    }
    return -1;
  };

  GE.contains = function(collection, value) {
    return GE.indexOf(collection, value) !== -1;
  };

  GE.uniq = function(array) {
    var results, seen;
    results = [];
    seen = [];
    _.each(array, function(value, index) {
      if (!GE.contains(seen, value)) {
        seen.push(value);
        return results.push(array[index]);
      }
    });
    return results;
  };

  GE.cloneData = function(o) {
    return JSON.parse(JSON.stringify(o));
  };

  GE.concatenate = function() {
    var rest;
    rest = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return _.flatten(rest, true);
  };

}).call(this);
