// Generated by CoffeeScript 1.6.3
(function() {
  var GE, globals,
    __slice = [].slice;

  globals = this;

  GE = {};

  globals.GE = GE;

  GE.makeConstantSet = function() {
    var obj, value, values, _i, _len;
    values = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    obj = {
      contains: function(value) {
        return value in obj;
      }
    };
    for (_i = 0, _len = values.length; _i < _len; _i++) {
      value = values[_i];
      obj[value] = value;
    }
    return Object.freeze(obj);
  };

  GE.logLevels = GE.makeConstantSet("ERROR", "WARN", "INFO", "LOG");

  GE.signals = GE.makeConstantSet("DONE", "ERROR");

}).call(this);
